apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: feature-1.yaml
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world from master"
